package com.a2.springboot.web.Assignment2.Request;

public enum RequestType {
    USER_COMMAND,USER_QUERY,ADMIN_COMMAND,ADMIN_QUERY,LOGIN_COMMAND,LOGIN_QUERY,REGISTER_COMMAND,REGISTER_QUERY,
    BOOK_COMMAND,BOOK_QUERY
}
